- name: Install Kubernetes Dependencies
  import_playbook: cluster-Dependencies.yml
  
  
- name: Initialaize Kubernetes Master
  import_playbook: master.yml
  
  
- name: Generating token from master and join worker nodes
  import_playbook: workers.yml
