# Import play books 
- name: Install Kubernetes Dependencies
  import_playbook: kube-dependencies.yml
- name: Initialaize Kubernetes Master
  import_playbook: master-cluster.yml
- name: Getting token from master and join workers
  import_playbook: workers-cluster.yml
